In [1]:
import numpy as np


## Tensors

In [3]:
zeroD_tensor=np.array(2)
zeroD_tensor.ndim

0

In [4]:
oneD_tensor=np.array([1,2,3,4])
oneD_tensor.ndim

1

In [6]:
twoD_tensor=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Two D tensor:\n",twoD_tensor)
print("Dimension of two D tensor:",twoD_tensor.ndim)

threeD_tensor=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print("Three D tensor:\n",threeD_tensor)
print("Dimension of three D tensor:",threeD_tensor.ndim)

Two D tensor:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of two D tensor: 2
Three D tensor:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Dimension of three D tensor: 3


## Matrix Multiplication

In [ ]:
mat1=[[1,2,3],[4,5,6],[7,8,9]]
mat2=[[10,11,12],[13,14,15],[16,17,18]]

result=[[0 for _ in range(len(mat2[0]))] for _ in range(len(mat1))]

for i in range(len(mat1)):
  for j in range(len(mat2[0])):
    for k in range(len(mat2)):
      result[i][j]+=mat1[i][k]*mat2[k][j]
      
print("Manual matrix mutltiplication result:")

for r in result:
  print(r)

Manual matrix mutltiplication result:
[84, 90, 96]
[201, 216, 231]
[318, 342, 366]


In [8]:
a=np.array(mat1)
b=np.array(mat2)
print("Numpy matrix multiplication result:\n",np.dot(a,b))

Numpy matrix multiplication result:
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
